// material-angular/src/app/components/lyrics/lyrics.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-lyrics',
  templateUrl: './lyrics.component.html',
  styleUrls: ['./lyrics.component.scss']
})
export class LyricsComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<section class="mat-typography">
  <h2 class="mat-display-2">Material Girl</h2>
  <h3 class="mat-subheading-1">Madonna, 1984</h3>

  <p>Some boys kiss me, some boys hug me<br/>
    I think they're okay<br/>
    If they don't give me proper credit, I just walk away<br/>
    They can beg and they can plead<br/>
    But they can't see the light, that's right<br/>
    'Cause the boy with the cold hard cash is always Mister Right</p>

  <p>
    'Cause we are living in a material world<br/>
    And I am a material girl<br/>
    You know that we are living in a material world<br/>
    And I am a material girl</p>

  <p>
    Some boys romance, some boys slow dance<br/>
    That's all right with me<br/>
    If they can't raise my interest, then I have to let them be<br/>
    Some boys try, and some boys lie<br/>
    But I don't let them play, no way<br/>
    Only boys that save their pennies make my rainy day</p>

  <p>
    'Cause we are living in a material world<br/>
    And I am a material girl<br/>
    You know that we are living in a material world<br/>
    And I am a material girl<br/>
    Living in a material world<br/>
    And I am a material girl<br/>
    You know that we are living in a material world<br/>
    And I am a material girl</p>

  <p>
    Living in a material world (-terial)<br/>
    Living in a material world<br/>
    Living in a material world (-terial)<br/>
    Living in a material world</p>

  <p>
    Boys may come, and boys may go<br/>
    And that's all right, you see<br/>
    Experience has made me rich, and now they're after me</p>

  <p>
    'Cause everybody's living in a material world<br/>
    And I am a material girl<br/>
    You know that we are living in a material world<br/>
    And I am a material girl<br/>
    Living in a material world<br/>
    And I am a material girl<br/>
    You know that we are living in a material world<br/>
    And I am a material girl</p>
</section>

// material-vue/src/components/Lyrics.vue
<template>
    <div>
        <h2 class='md-display-2'>Material Girl</h2>
        <h3 class='md-subheading'>Madonna, 1984</h3>
        <p>
            Some boys kiss me, some boys hug me<br/>
            I think they're okay<br/>
            If they don't give me proper credit, I just walk away<br/>
            They can beg and they can plead<br/>
            But they can't see the light, that's right<br/>
            'Cause the boy with the cold hard cash is always Mister Right</p>

        <p>
            'Cause we are living in a material world<br/>
            And I am a material girl<br/>
            You know that we are living in a material world<br/>
            And I am a material girl</p>

        <p>
            Some boys romance, some boys slow dance<br/>
            That's all right with me<br/>
            If they can't raise my interest, then I have to let them be<br/>
            Some boys try, and some boys lie<br/>
            But I don't let them play, no way<br/>
            Only boys that save their pennies make my rainy day</p>

        <p>
            'Cause we are living in a material world<br/>
            And I am a material girl<br/>
            You know that we are living in a material world<br/>
            And I am a material girl<br/>
            Living in a material world<br/>
            And I am a material girl<br/>
            You know that we are living in a material world<br/>
            And I am a material girl</p>

        <p>
            Living in a material world (-terial)<br/>
            Living in a material world<br/>
            Living in a material world (-terial)<br/>
            Living in a material world</p>

        <p>
            Boys may come, and boys may go<br/>
            And that's all right, you see<br/>
            Experience has made me rich, and now they're after me</p>

        <p>
            'Cause everybody's living in a material world<br/>
            And I am a material girl<br/>
            You know that we are living in a material world<br/>
            And I am a material girl<br/>
            Living in a material world<br/>
            And I am a material girl<br/>
            You know that we are living in a material world<br/>
            And I am a material girl</p>
    </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h2 {
  margin-bottom: 0;
  margin-top: 1rem
}
h3 {
  margin-top: 0;
}
</style>
