// material-angular/src/app/components/table/table.component.ts
import { Component, AfterViewInit, ViewChild } from '@angular/core';
import { MatPaginator, MatSort, MatTableDataSource } from '@angular/material';
import { SelectionModel } from '@angular/cdk/collections';

export interface FoodEntry {
  id: number,
  name: string,
  calories: number,
  fat: number,
  carbs: number,
  protein: number
}

@Component({
  selector: 'app-form',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.scss']
})
export class TableComponent implements AfterViewInit {

  private counter: number = 0;
  private selection: SelectionModel<FoodEntry>;
  private displayedColumns = ['name', 'calories', 'fat', 'carbs', 'protein'];
  private dataSource: MatTableDataSource<FoodEntry>;

  @ViewChild(MatPaginator) paginator: MatPaginator;
  @ViewChild(MatSort) sort: MatSort;

  constructor() {
    // Create mock entries
    const entries: FoodEntry[] = [
      this.createData('Cupcake', 305, 3.7, 67, 4.3),
      this.createData('Donut', 452, 25.0, 51, 4.9),
      this.createData('Eclair', 262, 16.0, 24, 6.0),
      this.createData('Frozen yoghurt', 159, 6.0, 24, 4.0),
      this.createData('Gingerbread', 356, 16.0, 49, 3.9),
      this.createData('Honeycomb', 408, 3.2, 87, 6.5),
      this.createData('Ice cream sandwich', 237, 9.0, 37, 4.3),
      this.createData('Jelly Bean', 375, 0.0, 94, 0.0),
      this.createData('KitKat', 518, 26.0, 65, 7.0),
      this.createData('Lollipop', 392, 0.2, 98, 0.0),
      this.createData('Marshmallow', 318, 0, 81, 2.0),
      this.createData('Nougat', 360, 19.0, 9, 37.0),
      this.createData('Oreo', 437, 18.0, 63, 4.0)
    ];

    // Assign the data to the data source for the table to render
    this.dataSource = new MatTableDataSource(entries);
    const initialSelection = [];
    const allowMultiSelect = true;
    this.selection = new SelectionModel<FoodEntry>(allowMultiSelect, initialSelection);
  }

  ngAfterViewInit() {
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.dataSource.data.length;
    return numSelected == numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.dataSource.data.forEach(row => this.selection.select(row));
  }

  private createData(name, calories, fat, carbs, protein): FoodEntry {
    this.counter += 1;
    return {id: this.counter, name, calories, fat, carbs, protein};
  }
}

<div class="example-container mat-elevation-z8">
  <mat-table [dataSource]="dataSource" matSort>

    <!-- Selection Column -->
    <ng-container matColumnDef="select">
      <mat-header-cell *matHeaderCellDef>
        <mat-checkbox (change)="$event ? masterToggle() : null"
                      [checked]="selection.hasValue() && isAllSelected()"
                      [indeterminate]="selection.hasValue() && !isAllSelected()">
        </mat-checkbox>
      </mat-header-cell>
      <mat-cell *matCellDef="let row">
        <mat-checkbox (click)="$event.stopPropagation()"
                      (change)="$event ? selection.toggle(row) : null"
                      [checked]="selection.isSelected(row)">
        </mat-checkbox>
      </mat-cell>
    </ng-container>

    <!-- Name Column -->
    <ng-container matColumnDef="name">
      <mat-header-cell *matHeaderCellDef mat-sort-header> Dessert (100g serving) </mat-header-cell>
      <mat-cell *matCellDef="let row"> {{row.name}} </mat-cell>
    </ng-container>

    <!-- Calories Column -->
    <ng-container matColumnDef="calories">
      <mat-header-cell *matHeaderCellDef mat-sort-header> Calories </mat-header-cell>
      <mat-cell *matCellDef="let row"> {{row.calories}} </mat-cell>
    </ng-container>

    <!-- Fat Column -->
    <ng-container matColumnDef="fat">
      <mat-header-cell *matHeaderCellDef mat-sort-header> Fat (g) </mat-header-cell>
      <mat-cell *matCellDef="let row"> {{row.fat}} </mat-cell>
    </ng-container>

    <!-- Carbs Column -->
    <ng-container matColumnDef="carbs">
      <mat-header-cell *matHeaderCellDef mat-sort-header> Carbs (g) </mat-header-cell>
      <mat-cell *matCellDef="let row"> {{row.carbs}} </mat-cell>
    </ng-container>

    <!-- Protein Column -->
    <ng-container matColumnDef="protein">
      <mat-header-cell *matHeaderCellDef mat-sort-header> Protein (g) </mat-header-cell>
      <mat-cell *matCellDef="let row"> {{row.protein}} </mat-cell>
    </ng-container>

    <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
    <mat-row *matRowDef="let row; columns: displayedColumns;">
    </mat-row>
  </mat-table>

  <mat-paginator [pageSizeOptions]="[10, 25, 50, 100]"></mat-paginator>
</div>

// material-vue/src/components/Table.vue
<template>
  <div>
    <h2 class='md-display-2'>A Fancy Table</h2>
    <md-table v-model="tableData" md-card @md-selected="onSelect" md-sort="name" md-sort-order="asc" >
      <md-table-row slot="md-table-row" slot-scope="{ item }" md-selectable="multiple" md-auto-select>
        <md-table-cell md-label="Dessert (100g serving)" md-sort-by="name">{{ item.name }}</md-table-cell>
        <md-table-cell md-label="Calories" md-sort-by="calories" md-numeric>{{ item.calories }}</md-table-cell>
        <md-table-cell md-label="Fat (g)" md-sort-by="fat" md-numeric>{{ item.fat }}</md-table-cell>
        <md-table-cell md-label="Carbs (g)" md-sort-by="carbs" md-numeric>{{ item.carbs }}</md-table-cell>
        <md-table-cell md-label="Protein (g)" md-sort-by="protein" md-numeric>{{ item.protein }}</md-table-cell>
      </md-table-row>
    </md-table>
  </div>
</template>

<script>
  let counter = 0;

  function createData(name, calories, fat, carbs, protein) {
    counter += 1;
    return {id: counter, name, calories, fat, carbs, protein};
  }

  export default {
    name: 'TableMultiple',
    data: () => ({
      selected: [],
      columnData: [
      	{id: 'name', label: 'Dessert (100g serving)'},
      	{id: 'calories', label: 'Calories'},
      	{id: 'fat', label: 'Fat (g)'},
      	{id: 'carbs', label: 'Carbs (g)'},
      	{id: 'protein', label: 'Protein (g)'}
      ],
      tableData: [
          createData('Cupcake', 305, 3.7, 67, 4.3),
          createData('Donut', 452, 25.0, 51, 4.9),
          createData('Eclair', 262, 16.0, 24, 6.0),
          createData('Frozen yoghurt', 159, 6.0, 24, 4.0),
          createData('Gingerbread', 356, 16.0, 49, 3.9),
          createData('Honeycomb', 408, 3.2, 87, 6.5),
          createData('Ice cream sandwich', 237, 9.0, 37, 4.3),
          createData('Jelly Bean', 375, 0.0, 94, 0.0),
          createData('KitKat', 518, 26.0, 65, 7.0),
          createData('Lollipop', 392, 0.2, 98, 0.0),
          createData('Marshmallow', 318, 0, 81, 2.0),
          createData('Nougat', 360, 19.0, 9, 37.0),
          createData('Oreo', 437, 18.0, 63, 4.0)
      ]
    }),
    methods: {
      onSelect (items) {
        this.selected = items
      }
    }
  }
</script>

<style scoped>
  h2 {
    margin-top: 1rem;
    margin-bottom: 1rem;
  }
  .md-table + .md-table {
    margin-top: 16px
  }
</style>
